# Generated by Django 5.2.6 on 2025-09-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contactinfo_sociallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='icon',
        ),
    ]
