# Generated by Django 5.2.6 on 2025-09-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteAssets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimage',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
