# Generated by Django 5.2.6 on 2025-09-30 16:43

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteAssets', '0003_alter_homeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1900, 1000], upload_to='article_images/', verbose_name='تصویر اصلی'),
        ),
    ]
