# Generated by Django 5.2.6 on 2025-09-22 09:23

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_courseinfo_alter_article_featured_image_courseimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر دوره ها'},
        ),
        migrations.AlterModelOptions(
            name='courseinfo',
            options={'ordering': ['-created_at'], 'verbose_name': 'دروه', 'verbose_name_plural': 'دوره های آموزشی'},
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1900, 1000], upload_to='course/course_images/'),
        ),
    ]
