# Generated by Django 5.2.6 on 2025-09-22 09:32

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_courseimage_options_alter_courseinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1900, 1000], upload_to='course/course_images/'),
        ),
    ]
