# Generated by Django 5.2.6 on 2025-09-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_courseimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلاً: جلسه اول - معرفی دوره', max_length=200, verbose_name='عنوان ویدیو')),
                ('youtube_url', models.URLField(help_text='لینک کامل ویدیو از یوتیوب را وارد کنید', verbose_name='لینک یوتیوب')),
                ('youtube_id', models.CharField(editable=False, help_text='به صورت خودکار از لینک استخراج می\u200cشود', max_length=50, unique=True, verbose_name='شناسه ویدیو')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'ویدیوی دوره',
                'verbose_name_plural': 'ویدیوهای دوره',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
