# Generated by Django 5.2.6 on 2025-09-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_videocast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocast',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'ویدیوی آپارات', 'verbose_name_plural': 'ویدیوهای آپارات'},
        ),
        migrations.RenameField(
            model_name='videocast',
            old_name='youtube_id',
            new_name='aparat_id',
        ),
        migrations.RemoveField(
            model_name='videocast',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='videocast',
            name='aparat_url',
            field=models.URLField(default='dsf', help_text='لینک کامل ویدیو از آپارات را وارد کنید', verbose_name='لینک آپارات'),
        ),
    ]
