# Generated by Django 5.2.6 on 2025-09-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_videocast_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocast',
            name='aparat_url',
            field=models.URLField(help_text='لینک کامل ویدیو از آپارات را وارد کنید', verbose_name='لینک آپارات'),
        ),
    ]
