# Generated by Django 5.2.6 on 2025-09-23 17:43

import django.db.models.deletion
import django_ckeditor_5.fields
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_videocast_aparat_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrialTourism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('base_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1900, 1000], upload_to='IndustrialTourism/base_images', verbose_name='تصویر اصلی')),
                ('video', models.FileField(blank=True, null=True, upload_to='IndustrialTourism/videos', verbose_name='ویدیو')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='محتوا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'گردشگری صنعتی',
                'verbose_name_plural': 'گردشگری\u200cهای صنعتی',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='courseimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر دوره\u200cها'},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='articles.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, max_length=500, verbose_name='خلاصه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1900, 1000], upload_to='article_images/', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='caption',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیح تصویر'),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.courseinfo', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1900, 1000], upload_to='course/course_images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='base_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1900, 1000], upload_to='course/base_images', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='مدت زمان دوره به ساعت', null=True, verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='منتشر شود'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروغ'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='teachers',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='نام اساتید'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.CreateModel(
            name='IndustrialTourismImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیح تصویر')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1900, 1000], upload_to='course/course_images/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('industrial_tourism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.industrialtourism', verbose_name='گردشگری صنعتی')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر دوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
