# Generated by Django 5.2.6 on 2025-09-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_industrialtourism_alter_courseimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industrialtourismimages',
            options={'ordering': ['-created_at'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر گردشگری صنعتی'},
        ),
    ]
