# Generated by Django 5.2.6 on 2025-09-23 17:52

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_industrialtourismimages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrialtourismimages',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1900, 1000], upload_to='IndustrialTourism/images', verbose_name='تصویر'),
        ),
    ]
