# Generated by Django 5.2.6 on 2025-10-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_industrialtourismimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
