# Generated by Django 5.2.6 on 2025-10-02 06:13

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[700, 1000], upload_to='article_images/', verbose_name='تصویر اصلی'),
        ),
    ]
