# Generated by Django 5.2.6 on 2025-10-02 06:14

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_article_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1900, 1000], upload_to='course/course_images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='base_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1900, 1000], upload_to='course/base_images', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='industrialtourism',
            name='base_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1900, 1000], upload_to='IndustrialTourism/base_images', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='industrialtourismimages',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1900, 1000], upload_to='IndustrialTourism/images', verbose_name='تصویر'),
        ),
    ]
