# Generated by Django 5.2.6 on 2025-10-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_article_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='مدت زمان دوره به دقیقه', null=True, verbose_name='مدت زمان'),
        ),
    ]
