# Generated by Django 5.2.6 on 2025-10-04 04:23

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_alter_courseinfo_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات'),
        ),
    ]
