# Generated by Django 5.2.6 on 2025-10-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0002_alter_communicationwithus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationwithus',
            options={'ordering': ['phone'], 'verbose_name': 'ارتباط با ما', 'verbose_name_plural': 'ارتباط با ما'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'موقعیت مکانی', 'verbose_name_plural': 'موقعیت مکانی'},
        ),
    ]
